name: Daily Data Build
on:
  schedule:
    - cron: '5 0 * * *'   # 每日 08:05 台北時間（GitHub 用 UTC）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci || npm i
      - run: npm run fetch:taibir
      - run: npm run fetch:cpi
      - run: npm run fetch:unemp
      - run: npm run fetch:m2


      - name: Commit updated JSON
        run: |
          git config user.name "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add docs/data/*.json || true
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: data refresh"
          git push
