name: Daily Data Build

on:
  schedule:
    - cron: '5 0 * * *'   # 每日 08:05 台北（GitHub 用 UTC）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Print env & repo state
        run: |
          node -v
          npm -v
          pwd
          ls -la
          echo "package.json:"
          cat package.json || true

      - name: Install deps
        run: npm ci --no-audit --no-fund || npm i

      - name: Ensure data folder
        run: mkdir -p docs/data

      - name: Run fetchers (non-blocking)
        run: |
          set -x
          npm run fetch:taibir || echo "::warning ::fetch:taibir failed"
          npm run fetch:cpi    || echo "::warning ::fetch:cpi failed"
          npm run fetch:unemp  || echo "::warning ::fetch:unemp failed"
          npm run fetch:m2     || echo "::warning ::fetch:m2 failed"

      - name: Ensure placeholders if missing
        run: |
          for f in taibir cpi unemployment m2; do
            [ -s docs/data/$f.json ] || echo "[]" > docs/data/$f.json
          done
          ls -la docs/data

      - name: Commit updated JSON
        run: |
          git config user.name "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add docs/data/*.json || true
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: data refresh"
          git push
